package dev.nimbuspowered.nimbus.template

import org.slf4j.LoggerFactory
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.exists
import kotlin.io.path.writeText

/**
 * Generates per-instance Geyser config for Velocity proxy services.
 * Each proxy instance gets its own Bedrock UDP port and must know
 * its local Java TCP port for protocol translation.
 */
class GeyserConfigGen {

    private val logger = LoggerFactory.getLogger(GeyserConfigGen::class.java)

    /**
     * Writes a Geyser config.yml that overrides port bindings and auth type.
     * Geyser will generate defaults for all other settings on first run.
     */
    fun generateGeyserConfig(workDir: Path, bedrockPort: Int, javaPort: Int) {
        val configDir = workDir.resolve("plugins").resolve("Geyser-Velocity")
        if (!configDir.exists()) configDir.createDirectories()

        val configFile = configDir.resolve("config.yml")
        configFile.writeText(buildString {
            appendLine("# Auto-generated by Nimbus — Geyser will fill in remaining defaults on first run")
            appendLine("bedrock:")
            appendLine("  address: 0.0.0.0")
            appendLine("  port: $bedrockPort")
            appendLine("remote:")
            appendLine("  address: 127.0.0.1")
            appendLine("  port: $javaPort")
            appendLine("  auth-type: floodgate")
            appendLine("passthrough-motd: true")
            appendLine("passthrough-player-counts: true")
            appendLine("passthrough-protocol-name: true")
        })

        logger.debug("Generated Geyser config: Bedrock UDP {} → Java TCP {}", bedrockPort, javaPort)
    }
}
