rootProject.name = "nimbus"

include("nimbus-core")
include("nimbus-protocol")
include("nimbus-agent")
include("nimbus-sdk")
include("nimbus-bridge")
include("nimbus-display")
include("nimbus-perms")
include("nimbus-module-api")
include("nimbus-module-perms")
include("nimbus-module-display")
include("nimbus-module-scaling")
include("nimbus-module-players")
include("nimbus-cli")
