id=display
name=Display
description=Server selector signs + NPCs via FancyNpcs
default=true
min_nimbus_version=0.1.0
main_class=dev.nimbuspowered.nimbus.module.display.DisplayModule
plugins=NimbusDisplay:nimbus-display.jar:plugins/nimbus-display.jar,FancyNpcs:FancyNpcs.jar:plugins/FancyNpcs.jar
