id=docker
name=Docker
description=Run services in Docker containers (hard memory/CPU limits, isolation, clean cleanup)
default=false
min_nimbus_version=0.9.0
main_class=dev.nimbuspowered.nimbus.module.docker.DockerModule
