id=resourcepacks
name=Resource Packs
description=Network-wide resource pack management (URL + locally hosted)
default=false
min_nimbus_version=0.1.0
main_class=dev.nimbuspowered.nimbus.module.resourcepacks.ResourcePacksModule
plugins=NimbusResourcePacks:nimbus-resourcepacks.jar:plugins/nimbus-resourcepacks.jar
