id=punishments
name=Punishments
description=Network-wide bans, mutes, kicks, and warnings
default=true
min_nimbus_version=0.1.0
main_class=dev.nimbuspowered.nimbus.module.punishments.PunishmentsModule
plugins=NimbusPunishments:nimbus-punishments.jar:plugins/nimbus-punishments.jar
